export {
  COMMENT_REPLY_STATUSES,
  COMMENT_TYPES,
  DEFAULT_REPLY_FORBIDDEN_WORDS,
  DUPLICATE_RISKS,
  assessCapturedCommentExtraction,
  assessDuplicateRisk,
  collectCommentsByUrl,
  createCommentCollectionBridge,
  createCommentReplyBatch,
  createCommentReplyForOne,
  createMainKeywordCandidates,
  generateContextualCaptureReplies,
  generateContextualCaptureReply,
  getCaptureOcrConfidenceStatus,
  isUsableCapturedComment,
  findForbiddenWords,
  normalizeComment,
  parseCapturedComments,
  parseManualComments,
  parseNaverCommentsFromText,
  resolveMainKeyword
} from "@shared/commentReplyGenerator.js";
